name: GitHub Actions Start
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Start Next.js app in background
        run: |
          npm run start &
          sleep 10

      - name: Run Cypress tests
        run: e2e:headless
        continue-on-error: true  

      - name: Upload Cypress videos
        if: always()
        uses: actions/upload-artifact@v2

        with:
          name: cypress-videos
          path: cypress/videos

      - name: Upload Cypress screenshots (optionnel)
        if: always()
        uses: actions/upload-artifact@v2

        with:
          name: cypress-screenshots
          path: cypress/screenshots